#!/usr/bin/env python3
"""
Generate the list of libultra names the runtime really implements.

match_libultra.py will only apply a name when the runtime supplies
`<name>_recomp`, because naming a function the runtime does not implement turns
interception into an undefined-reference link error. That list was maintained by
hand and drifted: names the runtime does implement were missing, so valid
matches (osPfsInit, osEPiRawReadIo, ...) were rejected and left unapplied.

Two kinds of definition must not be treated as implementations:

  * trap stubs, whose body reports "Stub `<name>` function called!" and exits.
    These link fine but abort at runtime the moment the game calls them, which
    is strictly worse than recompiling the real body. osEPiRawStartDma was one,
    and naming it took a working boot down.
  * the recompiler's own symbol lists, which say what N64Recomp renames, not
    what the runtime provides.

Run from the repository root; writes the list to stdout or --output.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# `void name_recomp(` with an optional extern "C", capturing the bare name.
DEF_RE = re.compile(
    r'^\s*(?:extern\s+"C"\s+)?void\s+([A-Za-z_][A-Za-z0-9_]*)_recomp\s*\(', re.M)
# A trap stub announces itself; the text is stable across the runtime.
TRAP_RE = re.compile(r'"Stub [`\']')


def body_after(text: str, start: int) -> str:
    """Returns the brace-matched body of the definition beginning at start."""
    open_brace = text.find("{", start)
    if open_brace < 0:
        return ""
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace:i + 1]
    return text[open_brace:]


def main() -> int:
    ap = argparse.ArgumentParser(description="list libultra names the runtime implements")
    ap.add_argument("--runtime", type=Path, default=Path("lib/N64ModernRuntime"),
                    help="runtime checkout to scan")
    ap.add_argument("--output", type=Path, help="write here instead of stdout")
    ap.add_argument("--show-traps", action="store_true",
                    help="also report the trap stubs that were excluded")
    args = ap.parse_args()

    impls: dict[str, str] = {}
    traps: dict[str, str] = {}

    for path in sorted(args.runtime.rglob("*.cpp")) + sorted(args.runtime.rglob("*.c")):
        parts = set(path.parts)
        # Skip build trees and the recompiler's own symbol tables.
        if parts & {"cmake-build", "build", "thirdparty"} or path.name == "symbol_lists.cpp":
            continue
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue
        for m in DEF_RE.finditer(text):
            name = m.group(1)
            where = f"{path.as_posix()}"
            if TRAP_RE.search(body_after(text, m.end())):
                traps[name] = where
            else:
                impls.setdefault(name, where)

    # A trap definition disqualifies the name even if something else defines it.
    for name in traps:
        impls.pop(name, None)

    lines = [
        "# libultra names the runtime implements as <name>_recomp.",
        "# Generated by tools/gen_runtime_impls.py -- do not edit by hand.",
        "#",
        "# Naming a function absent from this list turns interception into an",
        "# undefined reference. Trap stubs are deliberately excluded: they link",
        "# but abort as soon as the game calls them.",
        "",
    ] + sorted(impls)

    out = "\n".join(lines) + "\n"
    if args.output:
        args.output.write_text(out, newline="\n")
        print(f"  {len(impls)} implementations -> {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(out)

    if args.show_traps:
        print(f"\n  excluded {len(traps)} trap stub(s):", file=sys.stderr)
        for name, where in sorted(traps.items()):
            print(f"    {name:<24} {where}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
